import {
  ShoppingCart,
  UtensilsCrossed,
  Wrench,
  PawPrint,
  PartyPopper,
  Receipt,
  ShoppingBag,
  HeartPulse,
  RefreshCw,
  Gift,
  Percent,
  Smartphone,
  Home,
  Wallet,
  Fuel,
  ArrowLeftRight,
  HelpCircle,
  Target,
  Plane,
  Car,
  Heart,
  GraduationCap,
  Baby,
  Dog,
  Umbrella,
  PiggyBank,
  Utensils,
  Zap,
  Droplet,
  Shield,
  Stethoscope,
  Dumbbell,
  Palmtree,
  Camera,
  Music,
  Book,
  Briefcase,
  TreePine,
  Sparkles,
  Star,
  Coffee,
  Calendar,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  groceries: ShoppingCart,
  dining_out: UtensilsCrossed,
  vehicle: Wrench,
  pets: PawPrint,
  fun: PartyPopper,
  bills: Receipt,
  shopping: ShoppingBag,
  health_beauty: HeartPulse,
  subscriptions: RefreshCw,
  gifts_donations: Gift,
  tax_interest: Percent,
  telecom: Smartphone,
  mortgage_loans: Home,
  income: Wallet,
  transfer: Fuel,
  internal_transfer: ArrowLeftRight,
  uncategorized: HelpCircle,
};

export function categoryIcon(key: string): LucideIcon {
  return CATEGORY_ICONS[key] ?? HelpCircle;
}

// Curated set for goals/bills - user picks one rather than us guessing from
// free-text names.
export const PICKABLE_ICONS: { name: string; Icon: LucideIcon }[] = [
  { name: "Target", Icon: Target },
  { name: "Plane", Icon: Plane },
  { name: "Home", Icon: Home },
  { name: "Car", Icon: Car },
  { name: "Heart", Icon: Heart },
  { name: "Gift", Icon: Gift },
  { name: "GraduationCap", Icon: GraduationCap },
  { name: "Baby", Icon: Baby },
  { name: "Dog", Icon: Dog },
  { name: "PawPrint", Icon: PawPrint },
  { name: "Umbrella", Icon: Umbrella },
  { name: "PiggyBank", Icon: PiggyBank },
  { name: "Wallet", Icon: Wallet },
  { name: "ShoppingBag", Icon: ShoppingBag },
  { name: "Utensils", Icon: Utensils },
  { name: "Wrench", Icon: Wrench },
  { name: "Zap", Icon: Zap },
  { name: "Droplet", Icon: Droplet },
  { name: "Shield", Icon: Shield },
  { name: "Stethoscope", Icon: Stethoscope },
  { name: "Dumbbell", Icon: Dumbbell },
  { name: "Palmtree", Icon: Palmtree },
  { name: "Camera", Icon: Camera },
  { name: "Music", Icon: Music },
  { name: "Book", Icon: Book },
  { name: "Briefcase", Icon: Briefcase },
  { name: "TreePine", Icon: TreePine },
  { name: "Sparkles", Icon: Sparkles },
  { name: "Star", Icon: Star },
  { name: "Coffee", Icon: Coffee },
  { name: "Calendar", Icon: Calendar },
];

const PICKABLE_MAP = Object.fromEntries(PICKABLE_ICONS.map((p) => [p.name, p.Icon]));

export function pickedIcon(name: string | null | undefined): LucideIcon {
  return (name && PICKABLE_MAP[name]) || Target;
}
